CREATE TABLE FUNCIONARIO(
    ID INTEGER IDENTITY,
    NOME VARCHAR(250) NOT NULL,
    CPF  VARCHAR(250) NOT NULL,
    TELEFONE VARCHAR(250) NOT NULL,
    LOGIN VARCHAR(250) NOT NULL,
    SENHA VARCHAR(250) NOT NULL
);

CREATE TABLE GENERO(
    ID INTEGER IDENTITY,
    NOME VARCHAR(250) NOT NULL
);

CREATE TABLE FILME(
    ID INTEGER IDENTITY,
    NOME VARCHAR(250) NOT NULL,
    GENERO INTEGER NOT NULL,
    ANOLANCAMENTO INTEGER NOT NULL,
    RESUMO VARCHAR(500) NOT NULL,
    DURACAO TIME NOT NULL,
    INICIOCARTAZ DATE NOT NULL,
    FIMCARTAZ DATE NOT NULL,
    FOREIGN KEY (GENERO) REFERENCES GENERO(ID)
);

CREATE TABLE SALA(
    ID INTEGER IDENTITY,
    NOME VARCHAR(250) NOT NULL,
    LOTACAOMAX INT NOT NULL
);

CREATE TABLE SESSAO(
    ID INTEGER IDENTITY,
    HORARIO TIME NOT NULL,
    FILME INTEGER NOT NULL,
    SALA INTEGER NOT NULL,
    FOREIGN KEY (FILME) REFERENCES FILME(ID),
    FOREIGN KEY (SALA) REFERENCES SALA(ID)
);

CREATE TABLE VENDA(
    ID INTEGER IDENTITY,
    TIPO_INGRESSO VARCHAR(250) NOT NULL,
    SESSAO INTEGER NOT NULL,
    FOREIGN KEY (SESSAO) REFERENCES SESSAO(ID)
);